name: Process

on:
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时执行一次
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  GH_TOKEN: ${{ secrets.GH_TOKEN }}       # GitHub Gist Token
  GH_COOKIE: ${{ secrets.GH_COOKIE }}           # 可选 cookie
  SUBSCRIBE_CONF: ${{ secrets.SUBSCRIBE_CONF }}
  PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
  REACHABLE: ${{ vars.REACHABLE }}
  SKIP_ALIVE_CHECK: ${{ vars.SKIP_ALIVE_CHECK }}
  SKIP_REMARK: ${{ vars.SKIP_REMARK }}
  WORKFLOW_MODE: ${{ vars.WORKFLOW_MODE }}
  ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS }}

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run process.py
        run: |
          echo "Running process.py..."
          python3 subscribe/process.py -s subscribe/config/config.json -n 32 -t 12000 -f

      - name: Show timestamp
        run: date
